# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PozList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PozList
pod 'IQKeyboardManagerSwift', '5.0.0'
pod 'DKImagePickerController'
pod 'SkyFloatingLabelTextField', '~> 3.0'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'TGPControls'
pod 'GTProgressBar'
pod 'Alamofire', '~> 4.0’
pod 'SVProgressHUD'
pod 'RSKGrowingTextView'
pod 'AKSideMenu'
pod 'Fabric'
pod 'Crashlytics'

end
