# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PozList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PozList
pod 'InteractiveSideMenu'
pod 'IQKeyboardManagerSwift', '5.0.0'
pod 'DKImagePickerController'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'SkyFloatingLabelTextField', '~> 3.0'
end
